name: Bug Report
description: File a bug report
title: "[Bug Report]: Add Title"
type: Bug
projects: ["Bannerlord-Coop-Team/37"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: game-version
    attributes:
      label: Game version
      placeholder: "Example: v1.2.12"
    validations:
      required: true

  - type: input
    id: discord-link
    attributes:
      label: Discord Link
      description: Link to the related Discord discussion/thread/message if available.
      placeholder: "https://discord.com/channels/..."
    validations:
      required: false

  - type: textarea
    id: scenario
    attributes:
      label: Scenario
      placeholder: "Describe the scenario where the bug happened."
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe what happened. Give hex locations if you can.
      placeholder: "What happened? Include hex locations if possible."
    validations:
      required: true

  - type: input
    id: video-link
    attributes:
      label: Video link if available
      placeholder: "https://..."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots if available
      description: Drag and drop screenshots here, or paste them into this box.
      placeholder: "Add screenshots here."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. The log file exists where your Bannerlord.exe is, named Client_*.log or Server_*.log.
      render: shell
    validations:
      required: false
